export const BACKEND_URL = "https://pacific-springs-45597.herokuapp.com";

export const SET_SIGNIN_EMAIL = "SET_SIGNIN_EMAIL";
export const SET_SIGNIN_PASSWORD = "SET_SIGNIN_PASSWORD";
export const SUBMIT_SIGNIN_PENDING = "SUBMIT_SIGNIN_PENDING";
export const SUBMIT_SIGNIN_SUCCESS = "SUBMIT_SIGNIN_SUCCESS";
export const SUBMIT_SIGNIN_FAILED = "SUBMIT_SIGNIN_FAILED";

export const SET_REGISTER_NAME = "SET_REGISTER_NAME";
export const SET_REGISTER_EMAIL = "SET_REGISTER_EMAIL";
export const SET_REGISTER_PASSWORD = "SET_REGISTER_PASSWORD";
export const SUBMIT_REGISTER_PENDING = "SUBMIT_REGISTER_PENDING";
export const SUBMIT_REGISTER_SUCCESS = "SUBMIT_REGISTER_SUCCESS";
export const SUBMIT_REGISTER_FAILED = "SUBMIT_REGISTER_FAILED";

export const SET_IMAGE_URL = "SET_IMAGE_URL";
export const SUBMIT_IMAGE_PENDING = "SUBMIT_IMAGE_PENDING";
export const SUBMIT_IMAGE_SUCCESS = "SUBMIT_IMAGE_SUCCESS";
export const SUBMIT_IMAGE_FAILED = "SUBMIT_IMAGE_FAILED";
export const SET_IMAGE_COUNT = "SET_IMAGE_COUNT";
export const CHANGE_ROUTE = "CHANGE_ROUTE";