export const SET_SIGNIN_EMAIL = "SET_SIGNIN_EMAIL";
export const SET_SIGNIN_PASSWORD = "SET_SIGNIN_PASSWORD";
export const SUBMIT_SIGNIN_PENDING = "SUBMIT_SIGNIN_PENDING";
export const SUBMIT_SIGNIN_SUCCESS = "SUBMIT_SIGNIN_SUCCESS";
export const SUBMIT_SIGNIN_FAILED = "SUBMIT_SIGNIN_FAILED";

export const SUBMIT_SIGNOUT_PENDING = "SUBMIT_SIGNOUT_PENDING";
export const SUBMIT_SIGNOUT_SUCCESS = "SUBMIT_SIGNOUT_SUCCESS";
export const SUBMIT_SIGNOUT_FAILED = "SUBMIT_SIGNOUT_FAILED";

export const SET_REGISTER_NAME = "SET_REGISTER_NAME";
export const SET_REGISTER_EMAIL = "SET_REGISTER_EMAIL";
export const SET_REGISTER_PASSWORD = "SET_REGISTER_PASSWORD";
export const SUBMIT_REGISTER_PENDING = "SUBMIT_REGISTER_PENDING";
export const SUBMIT_REGISTER_SUCCESS = "SUBMIT_REGISTER_SUCCESS";
export const SUBMIT_REGISTER_FAILED = "SUBMIT_REGISTER_FAILED";

export const SET_IMAGE_URL = "SET_IMAGE_URL";
export const SUBMIT_IMAGE_PENDING = "SUBMIT_IMAGE_PENDING";
export const SUBMIT_IMAGE_SUCCESS = "SUBMIT_IMAGE_SUCCESS";
export const SUBMIT_IMAGE_FAILED = "SUBMIT_IMAGE_FAILED";
export const SET_IMAGE_COUNT = "SET_IMAGE_COUNT";

export const CLOSE_PROFILE_MODAL = "CLOSE_PROFILE_MODAL";
export const OPEN_PROFILE_MODAL = "OPEN_PROFILE_MODAL";
export const LOAD_PROFILE = "LOAD_PROFILE";
export const SET_PROFILE_NAME = "SET_PROFILE_NAME";
export const SET_PROFILE_AGE = "SET_PROFILE_AGE";
export const SET_PROFILE_PET = "SET_PROFILE_PET";
export const UPDATE_PROFILE_PENDING = "UPDATE_PROFILE_PENDING";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";
export const GET_PROFILE_PENDING = "GET_PROFILE_PENDING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

export const AUTHORIZE_TOKEN_PENDING = "AUTHORIZE_TOKEN_PENDING";
export const AUTHORIZE_TOKEN_SUCCESS = "AUTHORIZE_TOKEN_SUCCESS";
export const AUTHORIZE_TOKEN_FAILED = "AUTHORIZE_TOKEN_FAILED";
